# backend/Dockerfile
FROM node:20.5.0-alpine3.18
# Рабочая директория
WORKDIR /app
# Копируем package.json и 
# package-lock.json
COPY package*.json ./
# Устанавливаем зависимости
RUN npm install
# Копируем весь проект
COPY . .
# Собираем TypeScript
RUN npm run build
# Открываем порт контейнера
EXPOSE 3000
# Команда запуска